Repository xJoninha/Ecommerce-projeto-integrador, pull requests merged in 2022-06, with the labels that each got.

#27 feat: criei novos ejs para simular um filtro de produtos por enquanto…
  myApp/controller/IndexController.js
  myApp/public/images/garrafas/Belhara_Estate_Epic-TINTO.svg
  myApp/public/images/garrafas/Faruna-TINTO.svg
  myApp/public/images/garrafas/Los_Caserones-TINTO.svg
  myApp/public/images/garrafas/Tittarelli_Malbec-TINTO.svg
  myApp/public/images/garrafas/vinho-tantehue-tinto.svg
  myApp/public/images/garrafas/vinhoTinto/Alisios-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Armando-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Belhara-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Cainelli-cabernet-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Don-giovanni-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/La-couleur-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Las-falleras-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Los-andes-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Maturo-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Nube-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Sintonia-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Solear-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Terra-alegre-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Terras-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Travessia-tinto.jpg
  myApp/public/images/garrafas/vinhoTinto/Verse-tinto.jpg
  myApp/public/stylesheets/home-style.css
  myApp/public/stylesheets/vitrine-style.css
  myApp/routes/index.js
  myApp/views/home.ejs
  myApp/views/partials/header.ejs
  myApp/views/vitrine-branco.ejs
  myApp/views/vitrine-espumante.ejs
  myApp/views/vitrine-rose.ejs
  myApp/views/vitrine-tinto.ejs
Labels: documentation, enhancement, good first issue

#29 feat:alterando header, css do header e incluindo js para menu hamburg…
  myApp/public/images/svg/menu.svg
  myApp/public/stylesheets/header-style.css
  myApp/public/stylesheets/header-style.js
  myApp/views/partials/header.ejs
Labels: enhancement

#30 Feature/paginas sobre e tal
  assets/image/svg/menu.svg
  myApp/controller/IndexController.js
  myApp/public/stylesheets/pagina-sobre-e-tal.css
  myApp/routes/index.js
  myApp/views/partials/footer.ejs
  myApp/views/partials/header.ejs
  myApp/views/politica-privacidade.ejs
  myApp/views/sobre.ejs
  myApp/views/termos-uso.ejs
Labels: good first issue

#31 Reajusete na página HOME, e um efeito na vitrine :D
  myApp/public/stylesheets/home-style.css
  myApp/public/stylesheets/vitrine-style.css
  myApp/views/adega.ejs
  myApp/views/home.ejs
Labels: documentation, enhancement

#33 fix: reajusatando o hover dos cards
  myApp/public/stylesheets/home-style.css
Labels: bug, documentation, good first issue
