Repository xJoninha/Ecommerce-projeto-integrador, pull requests merged in 2022-05, with the labels that each got.

#8 Feature/footer
  assets/css/footer-style.css
  css/header-style.css
  css/image/creditCardsSvg/Amex.svg
  css/image/creditCardsSvg/ApplePay.svg
  css/image/creditCardsSvg/Boleto.svg
  css/image/creditCardsSvg/Diners.svg
  css/image/creditCardsSvg/Discover.svg
  css/image/creditCardsSvg/Elo.svg
  css/image/creditCardsSvg/GooglePay.svg
  css/image/creditCardsSvg/Hipercard.svg
  css/image/creditCardsSvg/Mastercard.svg
  css/image/creditCardsSvg/Visa.svg
  screens/footer.html
Labels: good first issue

#10 fix: caminho das pastas para não quebrar css e imagens
  screens/header.html
Labels: bug

#11 fix: caminho das pastas na adega
  screens/adega.html
  screens/footer.html
Labels: bug

#13 fix: fonte do footer
  assets/css/footer-style.css
  screens/footer.html
Labels: bug

#14 feat: reajuste de font-size e font-family
  assets/css/home-style.css
  screens/home.html
Labels: bug, documentation

#15 fix: svg adega no header
  screens/header.html
Labels: bug

#19 feat: primeiros passos para colocar uum carrocel um carrossel em noss…
  myApp/controller/controlerotaindex.js
  myApp/public/images/carrocelHome/banner-dia-vinho.png
  myApp/public/images/carrocelHome/banner-frete-gratis.png
  myApp/public/images/carrocelHome/banner-promocao.png
  myApp/public/stylesheets/home-style.css
  myApp/views/home.ejs
Labels: documentation, help wanted, good first issue

#20 feat: ajustando espaçamentos, alterando svg, fontes e tamanhos
  assets/css/footer-style.css
  assets/image/creditCardsSvg/cc-amex.svg
  assets/image/creditCardsSvg/cc-apple-pay.svg
  assets/image/creditCardsSvg/cc-barcode.svg
  assets/image/creditCardsSvg/cc-diners.svg
  assets/image/creditCardsSvg/cc-discover.svg
  assets/image/creditCardsSvg/cc-elo.svg
  assets/image/creditCardsSvg/cc-google-pay.svg
  assets/image/creditCardsSvg/cc-hipercard.svg
  assets/image/creditCardsSvg/cc-mastercard.svg
  assets/image/creditCardsSvg/cc-visa.svg
  screens/footer.html
Labels: enhancement

#21 fix: pequeno ajuste no efeito hover dos cards
  myApp/public/stylesheets/home-style.css
  myApp/views/home.ejs
Labels: bug, documentation

#22 Feature/arrumando footer ejs
  myApp/public/images/creditCardsSvg/cc-amex.svg
  myApp/public/images/creditCardsSvg/cc-apple-pay.svg
  myApp/public/images/creditCardsSvg/cc-barcode.svg
  myApp/public/images/creditCardsSvg/cc-diners.svg
  myApp/public/images/creditCardsSvg/cc-discover.svg
  myApp/public/images/creditCardsSvg/cc-elo.svg
  myApp/public/images/creditCardsSvg/cc-google-pay.svg
  myApp/public/images/creditCardsSvg/cc-hipercard.svg
  myApp/public/images/creditCardsSvg/cc-mastercard.svg
  myApp/public/images/creditCardsSvg/cc-visa.svg
  myApp/public/stylesheets/footer-style.css
  myApp/views/home.ejs
  myApp/views/partials/footer.ejs
Labels: bug

#23 feat: troquei o carrossel do Bootstrap pelo Slick Slider
  myApp/public/stylesheets/home-style.css
  myApp/views/home.ejs
Labels: documentation, enhancement, good first issue

#24 fix: dando alguns retoques principalmente na parte do carrossel
  myApp/public/stylesheets/home-style.css
  myApp/views/home.ejs
Labels: bug, documentation, enhancement

#25 feat: aqui começei a montar a página de 'vitrine', que vai ser a pági…
  myApp/controller/IndexController.js
  myApp/controller/controlerotaindex.js
  myApp/public/stylesheets/home-style.css
  myApp/public/stylesheets/vitrine-style.css
  myApp/routes/index.js
  myApp/views/adega.ejs
  myApp/views/arquivos ainda vazios/acompanharPedidos.ejs
  myApp/views/arquivos ainda vazios/categorias.ejs
  myApp/views/arquivos ainda vazios/contaCliente.ejs
  myApp/views/arquivos ainda vazios/finalizarCompra.ejs
  myApp/views/arquivos ainda vazios/login.ejs
  myApp/views/arquivos-ainda-vazios/acompanharPedidos.ejs
  myApp/views/arquivos-ainda-vazios/categorias.ejs
  myApp/views/arquivos-ainda-vazios/contaCliente.ejs
  myApp/views/arquivos-ainda-vazios/finalizarCompra.ejs
  myApp/views/arquivos-ainda-vazios/login.ejs
  myApp/views/cadastro.ejs
  myApp/views/home.ejs
  myApp/views/vitrine.ejs
Labels: documentation, good first issue
